# 1. Imagem Base
FROM node:18-alpine

# 2. Diretório de Trabalho
WORKDIR /usr/src/app

# 3. Copiar e Instalar Dependências
COPY package*.json ./
RUN npm install

# 4. Copiar Código-Fonte
COPY . .

# 5. Expor a Porta
EXPOSE 3000

# 6. Comando de Inicialização 
CMD [ "npm", "start" ]